// 기본 재료 분류·레시피·알레르기 묶음. 0.2.0 웹판(dist/app.js)의 데이터를 그대로 옮겼다.

enum Catalog {
    static let groups: [IngredientGroup] = [
        IngredientGroup(name: "곡물", items: ["밥", "쌀", "오트밀", "파스타"]),
        IngredientGroup(name: "채소", items: ["당근", "애호박", "브로콜리", "감자", "양파", "시금치", "단호박", "토마토"]),
        IngredientGroup(name: "단백질", items: ["달걀", "두부", "닭고기", "소고기", "연어"]),
        IngredientGroup(name: "과일", items: ["바나나", "사과"]),
        IngredientGroup(name: "양념", items: ["식용유", "간장", "참기름"]),
    ]

    static let allergens: [IngredientGroup] = [
        IngredientGroup(name: "달걀", items: ["달걀"]),
        IngredientGroup(name: "대두", items: ["두부", "간장"]),
        IngredientGroup(name: "밀", items: ["파스타", "간장"]),
        IngredientGroup(name: "생선", items: ["연어"]),
        IngredientGroup(name: "소고기", items: ["소고기"]),
        IngredientGroup(name: "닭고기", items: ["닭고기"]),
        IngredientGroup(name: "참깨", items: ["참기름"]),
    ]

    static let recipes: [Recipe] = [
        Recipe(id: "f1", name: "달걀 채소 볶음밥", audience: .family, ageMonths: 0, minutes: 15, emoji: "🍳",
               ingredients: ["밥", "달걀", "당근", "양파", "식용유"],
               amounts: ["밥 1공기", "달걀 1개", "당근 30g", "양파 ¼개", "식용유 1작은술"],
               steps: ["당근과 양파를 작게 다져 주세요.", "팬에 식용유를 두르고 채소를 부드러워질 때까지 볶아 주세요.", "달걀을 넣고 완전히 익힌 다음 밥을 넣어 2–3분 더 볶아 주세요."]),
        Recipe(id: "f2", name: "두부 채소 덮밥", audience: .family, ageMonths: 0, minutes: 20, emoji: "🍚",
               ingredients: ["밥", "두부", "애호박", "당근", "간장"],
               amounts: ["밥 1공기", "두부 100g", "애호박 50g", "당근 30g", "간장 1작은술", "물 80ml"],
               steps: ["두부와 채소를 작게 썰어 주세요.", "물에 당근과 애호박을 넣고 부드러워질 때까지 끓여 주세요.", "두부와 간장을 넣어 3분 더 끓인 뒤 밥 위에 올려 주세요."]),
        Recipe(id: "f3", name: "닭고기 감자 수프", audience: .family, ageMonths: 0, minutes: 30, emoji: "🥣",
               ingredients: ["닭고기", "감자", "양파"],
               amounts: ["닭고기 100g", "감자 1개", "양파 ¼개", "물 400ml"],
               steps: ["닭고기와 껍질 벗긴 감자, 양파를 작은 크기로 썰어 주세요.", "냄비에 재료와 물을 넣고 끓어오르면 중약불로 줄여 주세요.", "감자가 부드럽고 닭고기가 속까지 완전히 익을 때까지 20분가량 끓여 주세요."]),
        Recipe(id: "f4", name: "소고기 시금치 볶음밥", audience: .family, ageMonths: 0, minutes: 20, emoji: "🥬",
               ingredients: ["밥", "소고기", "시금치", "식용유"],
               amounts: ["밥 1공기", "다진 소고기 80g", "시금치 40g", "식용유 1작은술"],
               steps: ["시금치를 씻어 데친 뒤 물기를 짜고 잘게 썰어 주세요.", "기름을 두른 팬에 다진 소고기를 속까지 완전히 익혀 주세요.", "밥과 시금치를 넣고 고르게 섞어 볶아 주세요."]),
        Recipe(id: "f5", name: "토마토 달걀 볶음", audience: .family, ageMonths: 0, minutes: 12, emoji: "🍅",
               ingredients: ["토마토", "달걀", "식용유"],
               amounts: ["토마토 1개", "달걀 2개", "식용유 1작은술"],
               steps: ["토마토를 한입 크기로 썰고 달걀은 풀어 주세요.", "팬에 기름을 두르고 달걀을 완전히 익혀 따로 덜어 주세요.", "토마토를 부드럽게 볶은 뒤 달걀을 넣어 섞어 주세요."]),
        Recipe(id: "f6", name: "연어 브로콜리 한 접시", audience: .family, ageMonths: 0, minutes: 25, emoji: "🐟",
               ingredients: ["연어", "브로콜리", "식용유"],
               amounts: ["가시 제거한 연어 150g", "브로콜리 80g", "식용유 1작은술"],
               steps: ["브로콜리를 작은 송이로 나누어 충분히 찌세요.", "팬에 기름을 두르고 연어를 양면으로 구워 속까지 완전히 익혀 주세요.", "연어의 가시를 다시 확인하고 브로콜리와 함께 담아 주세요."]),
        Recipe(id: "f7", name: "포근한 채소 달걀찜", audience: .family, ageMonths: 0, minutes: 20, emoji: "🥚",
               ingredients: ["달걀", "당근", "애호박"],
               amounts: ["달걀 2개", "당근 20g", "애호박 30g", "물 120ml"],
               steps: ["채소를 잘게 다지고 달걀을 풀어 물과 섞어 주세요.", "내열 그릇에 넣고 뚜껑을 덮어 찜기에 올려 주세요.", "약 15분간 쪄서 가운데까지 완전히 익었는지 확인해 주세요."]),
        Recipe(id: "f8", name: "토마토 채소 파스타", audience: .family, ageMonths: 0, minutes: 25, emoji: "🍝",
               ingredients: ["파스타", "토마토", "양파", "식용유"],
               amounts: ["파스타 80g", "토마토 2개", "양파 ¼개", "식용유 1작은술"],
               steps: ["파스타를 제품 안내에 맞게 삶아 주세요.", "팬에 식용유를 두르고 잘게 썬 양파와 토마토를 볶아 주세요.", "물 3큰술을 더해 토마토가 풀어질 때까지 끓인 뒤 파스타를 넣어 섞어 주세요."]),
        Recipe(id: "b1", name: "소고기 애호박 쌀죽", audience: .baby, ageMonths: 6, minutes: 30, emoji: "🥣",
               ingredients: ["쌀", "소고기", "애호박"],
               amounts: ["쌀 20g", "다진 소고기 15g", "애호박 15g", "물 250ml"],
               steps: ["쌀을 충분히 불려 곱게 갈고 애호박을 잘게 다져 주세요.", "쌀과 물을 끓이다 소고기와 애호박을 넣어 고기가 완전히 익고 쌀이 푹 퍼질 때까지 저어 주세요.", "처음 먹는 아기는 덩어리 없이 곱게 갈아 주세요. 식힌 후 발달에 맞는 질감과 양으로 주세요."]),
        Recipe(id: "b2", name: "단호박 쌀죽", audience: .baby, ageMonths: 6, minutes: 25, emoji: "🎃",
               ingredients: ["쌀", "단호박"],
               amounts: ["쌀 20g", "씨와 껍질을 제거한 단호박 30g", "물 250ml"],
               steps: ["불린 쌀을 곱게 갈고 단호박을 푹 쪄 으깨 주세요.", "쌀과 물을 약불에서 저어가며 충분히 끓여 주세요.", "단호박을 넣고 고르게 섞어 끓인 뒤 필요하면 곱게 갈아 식혀 주세요."]),
        Recipe(id: "b3", name: "닭고기 당근 쌀죽", audience: .baby, ageMonths: 6, minutes: 30, emoji: "🥕",
               ingredients: ["쌀", "닭고기", "당근"],
               amounts: ["쌀 20g", "껍질과 뼈 없는 닭고기 15g", "당근 15g", "물 250ml"],
               steps: ["불린 쌀을 갈고 당근을 잘게 다져 주세요.", "닭고기를 속까지 완전히 익혀 잘게 다지거나 갈아 주세요.", "쌀과 당근을 물에 푹 끓이고 닭고기를 섞어 더 끓인 뒤 발달에 맞게 곱게 갈아 식혀 주세요."]),
        Recipe(id: "b4", name: "바나나 오트밀죽", audience: .baby, ageMonths: 6, minutes: 15, emoji: "🍌",
               ingredients: ["바나나", "오트밀"],
               amounts: ["무가당 오트밀 15g", "바나나 20g", "물 150ml"],
               steps: ["오트밀을 물에 넣고 약불로 충분히 익혀 주세요.", "바나나를 덩어리 없이 으깨 넣고 잠시 더 끓여 주세요.", "필요하면 갈아서 질감을 조절하고 미지근하게 식혀 주세요."]),
        Recipe(id: "b5", name: "두부 브로콜리 진밥", audience: .baby, ageMonths: 9, minutes: 20, emoji: "🥦",
               ingredients: ["밥", "두부", "브로콜리"],
               amounts: ["밥 50g", "두부 25g", "브로콜리 15g", "물 150ml"],
               steps: ["브로콜리의 질긴 줄기를 제거하고 푹 익혀 잘게 다져 주세요.", "두부를 익힌 뒤 으깨고 밥과 물을 함께 끓여 주세요.", "브로콜리를 넣고 밥알이 부드럽게 퍼질 때까지 익혀 주세요. 아이가 먹는 질감으로 더 으깨고 식혀 주세요."]),
        Recipe(id: "b6", name: "감자 당근 매시", audience: .baby, ageMonths: 6, minutes: 25, emoji: "🥔",
               ingredients: ["감자", "당근"],
               amounts: ["껍질 벗긴 감자 30g", "당근 15g", "끓인 물 적당량"],
               steps: ["감자와 당근을 작게 썰어 푹 쪄 주세요.", "숟가락으로 쉽게 눌릴 정도로 익었는지 확인해 주세요.", "곱게 으깨고 끓인 물로 부드러운 농도를 맞춰 식혀 주세요. 간식 또는 곁들임으로 주세요."]),
        Recipe(id: "b7", name: "소고기 채소 진밥", audience: .baby, ageMonths: 9, minutes: 25, emoji: "🍚",
               ingredients: ["밥", "소고기", "당근", "애호박"],
               amounts: ["밥 50g", "다진 소고기 20g", "당근 15g", "애호박 15g", "물 180ml"],
               steps: ["채소는 아주 잘게 다지고 소고기는 뭉치지 않게 풀어 주세요.", "물에 소고기를 넣어 완전히 익힌 뒤 채소와 밥을 넣어 주세요.", "모든 재료가 충분히 무르도록 끓이고 아이의 발달에 맞게 으깨 식혀 주세요."]),
        Recipe(id: "b8", name: "부드러운 채소 달걀찜", audience: .baby, ageMonths: 12, minutes: 20, emoji: "🥚",
               ingredients: ["달걀", "당근", "애호박"],
               amounts: ["달걀 1개", "당근 10g", "애호박 10g", "물 80ml"],
               steps: ["이미 먹어본 채소를 매우 잘게 다져 미리 부드럽게 익혀 주세요.", "달걀과 물을 풀어 채소를 섞고 내열 그릇에 담아 주세요.", "찜기에서 중심까지 완전히 익힌 후 식혀서 숟가락으로 작게 나누어 주세요."]),
    ]
}
